

export const USER_LOGIN_STATUS="USER_LOGIN_STATUS"
export const USER_LOGIN_RESPONSE = "USER_LOGIN_RESPONSE"
export const USER_LOGIN_ERROR = "USER_LOGIN_ERROR"

export const USER_RESGISTER_STATUS = "USER_RESGISTER_STATUS"
export const USER_RESGISTER_RESPONSE = "USER_RESGISTER_RESPONSE"
export const USER_RESGISTER_ERROR = "USER_RESGISTER_ERROR"

export const SHOW_GLOBAL_NOTIFICATION = "SHOW_GLOBAL_NOTIFICATION"
export const RESET_GLOBAL_NOTIFICATION = "RESET_GLOBAL_NOTIFICATION"


export const FORGET_PASSWORD_STATUS = "FORGET_PASSWORD_STATUS"
export const FORGET_PASSWORD_RESPONSE = "FORGET_PASSWORD_RESPONSE"
export const FORGET_PASSWORD_ERROR = "FORGET_PASSWORD_ERROR"

export const ROOM_REGISTER_STATUS = "ROOM_REGISTER_STATUS"
export const ROOM_REGISTER_RESPONSE = "ROOM_REGISTER_RESPONSE"
export const ROOM_REGISTER_ERROR = "ROOM_REGISTER_ERROR"

export const METADATA_POST_STATUS = "METADATA_POST_STATUS"
export const METADATA_POST_RESPONSE = "METADATA_POST_RESPONSE"
export const METADATA_POST_ERROR = "METADATA_POST_ERROR"

export const GET_METADATA_STATUS = "GET_METADATA_STATUS"
export const GET_METADATA_RESPONSE = "GET_METADATA_RESPONSE"
export const GET_METADATA_ERROR = "GET_METADATA_ERROR"

export const GET_ALL_SERVICE_STATUS = "GET_ALL_SERVICE_STATUS"
export const GET_ALL_SERVICE_RESPONSE = "GET_ALL_SERVICE_RESPONSE"
export const GET_ALL_SERVICE_ERROR = "GET_ALL_SERVICE_ERROR"