

export const USER_LOGIN_STATUS="USER_LOGIN_STATUS"
export const USER_LOGIN_RESPONSE = "USER_LOGIN_RESPONSE"
export const USER_LOGIN_ERROR = "USER_LOGIN_ERROR"

export const USER_RESGISTER_STATUS = "USER_RESGISTER_STATUS"
export const USER_RESGISTER_RESPONSE = "USER_RESGISTER_RESPONSE"
export const USER_RESGISTER_ERROR = "USER_RESGISTER_ERROR"

export const SHOW_GLOBAL_NOTIFICATION = "SHOW_GLOBAL_NOTIFICATION"
export const RESET_GLOBAL_NOTIFICATION = "RESET_GLOBAL_NOTIFICATION"